### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by gilgamsh** [andreasKroepelin/polylux#10]
Is there an elegant way to add Bibliography in each page? Thank you very much

**Comment by andreasKroepelin** [comment]
Are you thinking about something like footnotes? I would be interested in the concrete use cases for bibliographies per slide.

**Comment by TeddyHuang-00** [comment]
> I would be interested in the concrete use cases for bibliographies per slide.

BTW, are there any way to add bibliography in a dedicated slide? I just found it hard to do that as Typst will complain either `the bibliography does not contain this key` when the bibliography is under the main content block or `the document does not contain a bibliography` when bibliography is put into a slide container.

If not, I guess at least 25% people who will be seriously using this template will have similar needs, and being able to include bibliography definitely helps people moving from LaTeX beamer to this much more smoothly. So this might be a much preferable thing to have.

**Comment by andreasKroepelin** [comment]
Interesting. It looks like `#cite` and `#bibliography` currently don't work inside a `#locate` call. For implementation reasons, every slide currently has its content wrapped in a `#locate` call, though.

This will have to be fixed in the Typst compiler.

**Comment by andreasKroepelin** [comment]
I opened an issue for the Typst compiler. https://github.com/typst/typst/issues/785

**Comment by TeddyHuang-00** [comment]
> I opened an issue for the Typst compiler. https://github.com/typst/typst/issues/785

Great! Huge thanks for that! I shall keep an eye on it.

**Comment by gilgamsh** [comment]
> I opened an issue for the Typst compiler. [typst/typst#785](https://github.com/typst/typst/issues/785)

Thank you very much

**Comment by andreasKroepelin** [comment]
As long as this doesn't work, the issue should stay open, I would say. There's just not much we can do about it.

**Comment by andreasKroepelin** [comment]
This is probably going to work in Typst 0.6 🥳🥳
