### ISSUE TITLE
pdfpc doesnt work with notes

### ISSUE THREAD

**Issue by spooch99** [andreasKroepelin/polylux#101]
Testing with example "gauss.typ", I compiled it with typst v0.7.0:
typst compile gauss.typ --root ..

which worked (the "--root .." is necessary because of the reference to ../polylux.typ)

Then I build the gauss.pdfpc file with the new tool, which gave the exact file as delivered with git.

But unfortunatly no notes are shown (started with one screen with slide and note in parallel).

I tried pdfpc Version v4.5.1pre from ubuntu 22.04 und self compiled variant v4.7.0pre, both with the same result.

It seems, that the first slide shown on the left and the second slide in small right of this. In the next step the second slide in big and the third in small and so on.

TfH,
Oliver

**Comment by spooch99** [comment]
Hmm, original file from pdfpc-Website also doesnt work .. so the problem seems at my side

**Comment by drupol** [comment]
Hello,

I'm also having the issue with pdfpc, it doesn't show notes at all.

Also, why did you closed the issue? did you find a solution? Could you please let us know?
