### ISSUE TITLE
Resizing font to fit text on page

### ISSUE THREAD

**Issue by MilesCranmer** [andreasKroepelin/polylux#104]
Hi @andreasKroepelin,

Awesome package. I was wondering if there is any way to automatically resize text to fit on a single slide?

Cheers,
Miles

**Comment by andreasKroepelin** [comment]
Thanks a lot! :)

In the released version 0.3.1, there is `#fit-to-height` that you might want to look up here:
https://andreaskroepelin.github.io/polylux/book/utils/fit-to-height.html

Merging #96 will bring even more functionality in that direction.

**Comment by MilesCranmer** [comment]
Fantastic, thanks!
