### ISSUE TITLE
Feature request: `uncover-each`

### ISSUE THREAD

**Issue by MilesCranmer** [andreasKroepelin/polylux#105]
I'm not sure the best API for this, but it would be great if there was a way to automatically uncover bullet points one-by-one. This would be similar to the "Appear by Bullet" animation in keynote.

The current approach is to write `#uncover(i)[]` for each bullet. Maybe there is a way to generate that automatically?

**Comment by andreasKroepelin** [comment]
May I refer you to the book again:
https://andreaskroepelin.github.io/polylux/book/dynamic/obo-lbl.html

Is that what you are looking for?

**Comment by MilesCranmer** [comment]
Awesome, thanks! I missed it 🙂
