### ISSUE TITLE
[Feature Request] Visible indicators for `Covers`

### ISSUE THREAD

**Issue by javentous** [andreasKroepelin/polylux#130]
hey, thanks for the package, it's super cool and i hope to use it. the name was a bit strange (much + light = ??) but it makes sense with the projector lore.
---
when 1. attending lectures and viewing them asynchronously, as well as in a recording, i am at times caught off-guard by the introduction of elements in the fashion which is available at present, with `Cover` or with `Only`, which seems to exacerbate this issue as there are no animations which may guide the viewer (i.e. me) as to where  the content will be, and 2. when a prof or someone has an empty slide that starts with like one large bullet point, a large title, a small title, a large sentence, a small sentence (size here refers to the area it occupies on a slide, not length) it is _ambiguous_ how much content there will be on the slide (by the end of sort of revealing or showing all the content) which, in a time-constrained environment causes explainability to suffer (fighting with technology doesn't help...)  as there is _no visual indicator_ with which i can gauge prior to the reveal of the whole or entirety of the slide.

i suppose i could share mockups if you'd like, in order to get the meaning across if i haven't communicated it well. 

vis-à-vis solutions; i was thinking some kind of filter with some of the following qualities in part or in conjunction: blurring/diffuse effect, a rounded light grey (or other color) rectangle sort of like how _censored_ stuff or _confidential_ cia stuff looks but less harsh and less distracting, i have other stuff but i think i've written enough...

**Comment by andreasKroepelin** [comment]
#91 might be part of what you would like. Blurring filters etc. are currently not supported by Typst. Similarly, proper animations are not something you can do with PDFs.

I am closing this issue for now. Feel free to reopen it or add another comment if you feel like more discussion is needed.
