### ISSUE TITLE
Handout mode does not work

### ISSUE THREAD

**Issue by KronosTheLate** [andreasKroepelin/polylux#145]
Code:
```
#import "@preview/polylux:0.3.1": *
#import themes.simple: *
#show: simple-theme.with()
#enable-handout-mode(true)
#slide[
  - Point 1 #pause
  - Point 2
]
```
Output:
![image](https://github.com/andreasKroepelin/polylux/assets/61620837/d4c80781-eff7-4c76-9fe1-9a145c3622d3)

So it appears like setting `#enable-handout-mode(true)` has no effect. Am I doing it wrong, or is it broken?

**Comment by KronosTheLate** [comment]
Could it be that this was fixed in https://github.com/andreasKroepelin/polylux/commit/d52ff22898a4bc66a889d0180e3703e7d5988d7a? If yes, we can just close this.

**Comment by andreasKroepelin** [comment]
> Could it be that this was fixed in https://github.com/andreasKroepelin/polylux/commit/d52ff22898a4bc66a889d0180e3703e7d5988d7a? If yes, we can just close this.

Yep, should be fixed.
