### ISSUE TITLE
Order of code-lines affects content with given subslide-numbers

### ISSUE THREAD

**Issue by KronosTheLate** [andreasKroepelin/polylux#149]
The title only mentions one of the two issues shown below. I though it was the most concrete problem I could put into words. Feel free to edit the title.

Scenario 1: Works as expected
![image](https://github.com/andreasKroepelin/polylux/assets/61620837/9f08c001-4ded-48bb-ae60-a20d833833a9)

Scenario 2: Removing newline messes up highlighted area
![image](https://github.com/andreasKroepelin/polylux/assets/61620837/51ec0727-88e6-4d42-b91a-894dc238dadd)

Scenario 3: Highlight on final line leads to no highlighting
![image](https://github.com/andreasKroepelin/polylux/assets/61620837/3e6ebe55-a474-4877-bd67-d5b15ab9aac7)

Scenario 4: No newline and highlight on final, for completeness
![image](https://github.com/andreasKroepelin/polylux/assets/61620837/1960073f-75d3-4fce-b85c-820559bc3b58)

Tagging @OrangeX4 as the author of pinit, which provides the highlighting feature. I am not sure if this bug could be replicated without that package. I have used pinit version 0.1.3, and the master branch of polylux (a few commits ahead of 0.3.1.

**Comment by OrangeX4** [comment]
This is due to the fact that typst doesn't have a built-in `absolute-place`, so pinit uses a hack implementation where you need to add a blank line before `pinit-highlight`.

**Comment by KronosTheLate** [comment]
I just reproduced this in Touying, so it seems like all effects come from pinit. Is it possible to move this issue over there?

Code used in touying:
<details>

```
#import "@preview/touying:0.2.0": *
#import "@preview/pinit:0.1.3": *

#let s = (s.methods.enable-transparent-cover)(self: s)
#let (init, slide, uncover, only, alternatives) = utils.methods(s)
#show: init

#slide(repeat: 2, self => [
  #let (uncover, only, alternatives) = utils.methods(self)

  #uncover("1-")[#pin(1)Test#pin(2)]

  #only("2-")[#pinit-highlight(1, 2)]
  #uncover("2-")[Something new]

])
```

</details>

**Comment by OrangeX4** [comment]
Like I said, it has nothing to do with polylux or touying, it's caused by typst not having absolute-place, so you need to play more blank lines with pinit.

**Comment by KronosTheLate** [comment]
Right. As it is not a polylux-issue, it is only appropriate to close this.

It also sounds like you, as the author of pinit, is well aware, so I will not make a new issue there.

**Comment by OrangeX4** [comment]
Maybe I can add a warnning to the pinit readme, thanks for the issue.
