### ISSUE TITLE
[FR] A unified way to adjust colors

### ISSUE THREAD

**Issue by duskmoon314** [andreasKroepelin/polylux#159]
Currently, themes have predefined colors; only some provide options to adjust them. In beamer, we can use `\setbeamercolor` to adjust colors: `\setbeamercolor*{titlelike}{fg=black, bg=blue}`. A unified way to adjust colors is required.

However, it is difficult to implement this function in Typst since it has side effects. A proper way to do this needs more discussion.

**Comment by andreasKroepelin** [comment]
In fact, I will move away from a "unified approach" even more in the future. I think themes should just become Typst templates

**Comment by duskmoon314** [comment]
I see. Maintaining the polylux focused on the basic features of making slides sounds reasonable. Thus, we expect every theme to have its proper way of customizing its looks and other features.

Thanks for your answer.
