### ISSUE TITLE
How to fix incorrect heading numbering after a #pause in presentation slides?

### ISSUE THREAD

**Issue by AndreiZoltan** [andreasKroepelin/polylux#184]
I've previously [asked](https://forum.typst.app/t/how-to-fix-incorrect-heading-numbering-after-a-pause-in-presentation-slides/486)  this question, but I didn't receive an answer regarding how to resolve it with Polylux, so I'm reposting it here.

When using the following imports for writing theorems in a presentation, I noticed that after a `#pause` in a slide, the heading numbering increments unexpectedly.
```
#import "@preview/polylux:0.3.1": *
#import "@preview/ctheorems:1.1.2": *
#set heading(numbering: "1.")
#import themes.simple: *
#show: simple-theme.with(aspect-ratio: "4-3")
#slide[
== Introduction
bar

#pause
foo
]
```
On the second page, the heading changes to **0.2 Introduction**, which causes incorrect numbering for subsequent theorems. How can I prevent the heading from incrementing after a `#pause`?

**Comment by andreasKroepelin** [comment]
See #67 and typst/typst#1841
