### ISSUE TITLE
simple document make the compiler crash

### ISSUE THREAD

**Issue by astrale-sharp** [andreasKroepelin/polylux#20]
The following code panics with `thread 'main' panicked at 'assertion failed: min <= max', /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/cmp.rs:867:9`
Am I the only one?

It's probably a typst bug.
```
//".libs/plot.typ"

#import "../libs/slides.typ" : *

#show: slides.with(
    authors: "Mme Cercy",
    short-authors: "Mme Cercy",
    title: [Chapitre 6 -- activité 1: Correction],
    short-title: "correction activité 1",
    date: "Avril 2023"
)
#slide(title: "Question 4")[]
```

**Comment by palainp** [comment]
Could you try with a `#new-section("")`, even if it's empty, before the first slide?

**Comment by FWDekker** [comment]
I'm experiencing a similar bug; I think it's the same bug.

I have the latest `slides.typ` from master (at 8021edacb3b8023fdd8c47f20916761a19c5b779), and the following `main.typ`:

```typst
#import "slides.typ": *

#show: slides

#slide[]
```

This results in "The compiler has crashed."

Adding contents to `#slide[]` (e.g. `#slide[Foo bar]`) resolves the crash. Adding `#new-section("")` before `#slide[]` or even inside the `[]` of `#slide[]` does not resolve the issue.

I am also encountering the same issue with the following file:

```typst
#import "slides.typ": *

#show: slides

#slide[Foo]

#slide[Bar]
```

I am able to resole this error by adding a `(title: "")` to both slides. Without titles it just doesn't seem to work.

**Comment by palainp** [comment]
That's right, the _default theme_ needs either a title or, if not defined, a section string (which can be empty but not none).

With the default theme, adding `#new-section("")` at the begining of your document, before the first solide, should helps slides without title.

**Comment by palainp** [comment]
Ok I had some times, done in #42. But maybe that is a red hering and the underlying issue is elsewhere as a simple test case still passes:
```
#let test = state("test", none)
test.display()
```
(which display nothing) as expected.

**Comment by FWDekker** [comment]
@palainp I see, I was not aware of that. However, while adding a title fixes the issue in my second example, it does not resolve the issue with my first example. Specifically, the following code still causes a compiler crash:

```typst
#import "slides.typ": *

#show: slides

#new-section("")
#slide(title: "Title")[]
```

**Comment by palainp** [comment]
Oh this is very interesting, my version was quite old (0.2.0 and works fine), but the latest one (0.4.0) crashes. I'll try to look more into that (in the meantime, a workaround could be to downgrade your version if it doesn't lack any functionality?).

**Comment by palainp** [comment]
Update: would you mind to try with the updated slides.typ on my branch https://github.com/palainp/typst-slides/tree/fix-empty-section-name . If that works I'll set back the PR for review.
