### ISSUE TITLE
Obtain subslide number

### ISSUE THREAD

**Issue by Mc-Zen** [andreasKroepelin/polylux#40]
Hi, awesome work!

It would be helpful if there was a way to retrieve the current subslide number, for instance for highlighting cells in a table:

```
#table(
  fill: (row, col) => {
    if (subslide() == 2) return red
  },
  [a],[b]
)
```

I could not find a way to achieve this with `#only` and co. Did I overlook something?

**Comment by andreasKroepelin** [comment]
I think my approach to this would be something like
```typ
#let my-table(subslide) = table( /* your custom content depdending on the subslide argument */ )
#alternatives(my-table(1), my-table(2)
// or, if you don't want to type so much, especially for more than 2 different versions
#alternatives(..range(2).map(my-table))
```

Obtaining the subslide in general is a bit tricky due to how states/counters work in Typst.
But I think your use case can be solved quite neatly with the idea sketched above.

 Sorry if this help comes much too late :sweat_smile:

**Comment by Mc-Zen** [comment]
I love it :D
