### ISSUE TITLE
Add background support for custom themes

### ISSUE THREAD

**Issue by w568w** [andreasKroepelin/polylux#41]
The ability to customize the background of slides via user-built themes would be a fantastic feature.

I come up with a really simple solution to let theme creators decide that for their own themes:

1. In `slides()`, read special variants from the theme:
```
let the-theme = theme(data)
set page(
    paper: "presentation-" + aspect-ratio,
    margin: 0pt,
    background: the-theme.at("theme:background", default: none) // here
)
```
2. In user's theme factory function, return with this special key:
```
let background = place(
    top + left,
    dx: 80% - 11cm / 2,
    dy: 25%,
    image(
        "my-university-or-company-logo.png", width: 11cm
    )
)

// ...

(
    "title slide": title-slide,
    "default": default,
    "wake up": wake-up,
    "theme:background": background
)
```

And that's done. I patched `slides.typ` to show how this option works in my own slides :

![](https://github.com/andreasKroepelin/typst-slides/assets/8389787/38bd118d-9bd9-4c43-88b0-d2f0bffe7241)

**Comment by andreasKroepelin** [comment]
Interesting idea! I'm a bit unhappy with how the themes currently work anyways. I'll just need to find time (and a good plan) to refactor all that. Everything would be so much simpler with set rules for custom functions!
