### ISSUE TITLE
Consider using page header+footer for slides

### ISSUE THREAD

**Issue by ModProg** [andreasKroepelin/polylux#48]
Having some text that cannot be manually split over multiple pages like, e.g., a bibliography (not yet working with typst-slides but hopefully soon TM https://github.com/typst/typst/issues/785).

I experimented a bit, and this seems to work:
```rs
#style(styles => {
    let header = block(
        width: 100%,
        inset: (x:.5em, y:.7em),
        stroke: (bottom: 1mm + red),
        grid(columns: (1fr, 1fr),
            image("logo.svg", width: 2cm),
            align(right)[Header]
        )
        
    )
    let footer = block(
        width: 100%,
        inset: (x:.5em, y:.7em),
        stroke: (top: 1mm + red),
        align(right)[Footer]
    )
    page(width: 5cm, height: 5cm, margin: (x: 3%, 
      top: measure(header, styles).height + .5em, 
      bottom: measure(footer, styles).height + .5em), 
      header: header, header-ascent: .5em, 
      footer:footer, footer-descent: .5em, 
      lorem(50))
})
``` 
![grafik](https://github.com/andreasKroepelin/typst-slides/assets/11978847/9da0f2b7-6dcf-4bc5-afba-6affce766acb)

Currently, stuff like that breaks the layouting:
![grafik](https://github.com/andreasKroepelin/typst-slides/assets/11978847/63e28eb3-4065-47da-91ab-45209199a6ae)

**Comment by ModProg** [comment]
though this would require a theme redesign as mentioned in https://github.com/andreasKroepelin/typst-slides/issues/41#issuecomment-1565306723

**Comment by andreasKroepelin** [comment]
I actually used `header` and `footer` in the beginning but then felt that theme design is much simpler if every piece of layout is just handled by the theme author. But you are right that this fails for content that doesn't fit on one slide... As you already remarked, this is strongly tied to rethinking how theming should work. I'll have some long travels soon, hopefully I'll find some time!
