### ISSUE TITLE
Speaker notes

### ISSUE THREAD

**Issue by zouharvi** [andreasKroepelin/polylux#52]
First of all, amazing project (or [a package](https://github.com/typst/typst/commit/7b92bd7c340d9f9c094ed2fa57912049317d9b20)?) which I used for my PhD proposal presentation.

I wanted to start a discussion around speaker notes and how to implement it and which features it should contain (happy to help out).
It seems natural that `speaker-notes` would be a named argument to `slide` and that there would be a global switch: `#show: slides.with( /* ... */, notes: true )` which would print them out, likely underneath the slide (this would mean changing the aspect ratio etc).

Currently I have the notes on separate slides with custom theme variant which are turned off based on a state:
```
#let notes(body) = {
  locate(loc => {
    if notes-mode.at(loc) {
        slide(theme-variant: "notes", body)
    } 
  })
}
```

**Comment by andreasKroepelin** [comment]
Interesting idea and I'm glad this template was useful to you!

I think the usability of speaker notes depends a lot on the PDF viewer. I have personally never used such notes, so it would be interesting to see how people do that with PDF based presentations.

**Comment by JuliusFreudenberger** [comment]
I used LaTeX Beamer to create PDF based presentations in the past.
Basically, there are two options:
1. Using the beamer option `show notes on second screen`, which doubles the pdf width and shows the LaTeX rendered notes on the right half. A presenting program like [dspdfviewer](https://github.com/dannyedel/dspdfviewer) can be used, which splits the slides again and has a presenter view.
2. Using [pdfpc](https://github.com/pdfpc/pdfpc) and their notes system. When you start a presentation in pdfpc, you can add Markdown styled notes to every pdf page, which are saved in a separate `*.pdfpc` file. Alternatively, there is [latex-pdfpc](https://github.com/pdfpc/latex-pdfpc), which is a LaTeX package which allows to specify these notes directly in the code.

I reckon, the first approach should be easier to accomplish in Typst, as I do not know how well the possiblity to manipulate the PDF document is or if it is possible to write a separate file.

I used the latter in my last presentations, which worked quite well.
My last presentation (my Bachelor's presentation) was the first I did in typst with your bristol template and I loved it! I added the speaker notes with pdfpc after creating the presentation slides, which worked but was a bit cumbersome. I would love the addition of "built-in" speaker notes!

**Comment by andreasKroepelin** [comment]
For reference, I will link to https://github.com/typst/typst/issues/1746 here. That would be my preferred solution for this. And I didn't know pdfpc before, that's pretty cool!
