### ISSUE TITLE
Adding typst-slides to the offical packages repository

### ISSUE THREAD

**Issue by AndyBarcia** [andreasKroepelin/polylux#53]
Typst just added support for packages through a Github [repository](https://github.com/typst/packages/tree/main), so it's probably a good idea to add this template as an official package.

There's just a problem though.  The submission guidelines state that the package state that the package name can't contain neither "typst", nor generic descriptive words (like "slides"). So it needs a new name.

**Comment by andreasKroepelin** [comment]
This is on my todo list, I hope to find time for that soon. A current naming idea is `polylux` in resemblance to LaTeX's `beamer`.
