### ISSUE TITLE
Allow themes to `set()` options globally

### ISSUE THREAD

**Issue by freundTech** [andreasKroepelin/polylux#55]
Currently themes are restricted to changing things within a page. Sometimes it might however be useful to change things globally, for example when setting a font or changing the page size (the later of which currently isn't possible at all as far as I can tell).

This could be done by adding an `init` or `setup` function to themes, which can produce arbitrary content before the first slide is rendered.
It's not possible to add this to the top-level of the theme function, as it has to return the dictionary of theme-variants and therefor can't return content.

**Comment by andreasKroepelin** [comment]
This will be solved after I finish the current redesign of the theming logic.
