### ISSUE TITLE
Book is no longer online?

### ISSUE THREAD

**Issue by ntjess** [andreasKroepelin/polylux#57]
Are the demo github.io links supposed to still be valid? Visiting the [url](https://andreaskroepelin.github.io/typst-slides/book/) referenced in the example slides now results in a 404.

**Comment by ntjess** [comment]
Oh, I see the repo name changed to `polylux`, so changing the link to https://andreaskroepelin.github.io/polylux/book/ fixes the issue.

**Comment by andreasKroepelin** [comment]
Aware of that, I'm in the process of fixing all that (see `prepare-package` branch).
