### ISSUE TITLE
Add institution and institution's logo like beamer.

### ISSUE THREAD

**Issue by jlduu** [andreasKroepelin/polylux#58]
Add institution and institution's logo like beamer.

**Comment by jlduu** [comment]
> Can you please elaborate on that? This issue is not very helpful in its current form.

Thanks for developing such a perfect slides package for typst. If polylux is used to make slides for academic presentations, scholars like to add information such as the name of their institution, logo, email, and personal website. I am wondering whether these functions can be provided as options to meet the individual needs of users.

**Comment by jlduu** [comment]
> Can you have a look at the themes (https://andreaskroepelin.github.io/polylux/book/themes/gallery/index.html) and report if you find something that does what you need there?

Many many thanks, I try this new version for all day, it's very perfect and addresses all my concerns.

**Comment by andreasKroepelin** [comment]
Great, I'll close this then!
