### ISSUE TITLE
Accessing theme helpers while developing an external theme (`logic.*`)

### ISSUE THREAD

**Issue by jemus42** [andreasKroepelin/polylux#64]
Thanks for the package, this is what finally got me to try learning typst! :)

I started building my theme from scratch, starting with

```
#import "@preview/polylux:0.2.0": *
```

However, when trying to implement a slide counter, [the book](https://andreaskroepelin.github.io/polylux/book/themes/helpers.html#how-much-longer-) refers me to: 

```
#logic.logical-slide.display()
``` 

The online editor then lets me know that `logic` is an unknown variable, and as far as I can see I don't have any way of accessing these helpers without directly importing `logic.typ` locally, is that correct?

Since I'm trying to replicate my institute's slide template, I'm currently not working under the assumption of adding this theme to polylux anytime toon, so I'm wondering how feasible it is to develop a "proper" theme using just the polylux package import.

Then again, since I literally started learning typst yesterday I fully assume that I may just be holding it wrong 😅

**Comment by jemus42** [comment]
Apologies, just saw #61 🥴

**Comment by andreasKroepelin** [comment]
Maybe I should note this in the docs as this is the third time it came up 😅 Sorry for the inconvenience!
