### ISSUE TITLE
Alternatives: repeat-last

### ISSUE THREAD

**Issue by Mc-Zen** [andreasKroepelin/polylux#66]
Hi there,

I'd like to suggest something like a boolean `repeat-last` option for `alternatives`. This takes only effect if other stuff on the slide generates more subslides than options given to `alternative`. Then, the last alternative is "held" instead of showing nothing. 

This would be useful for slides with several visual components.

**Comment by andreasKroepelin** [comment]
Sounds like a good idea and easy to do. I will implement this when I'm back from vacation.
