### ISSUE TITLE
Broken memoization with "simple" theme

### ISSUE THREAD

**Issue by sitandr** [andreasKroepelin/polylux#68]
I found that incremental compilation doesn't work when using "simple" theme (recompilation works approximately the same time as compilation). I found I could fix it if I remove line `show outline.entry: it => it.body`.

My presentation is pretty simple, even no outline, just lots of code highlighting. It is easy to reproduce on smaller slides, but the difference is not that noticable. Currently I have no idea why is it happening, but I guess it is related to state management. Maybe it is worth to temporaly remove that line to prevent the problem.

**Comment by andreasKroepelin** [comment]
Interesting... 🤔 I have never actually created large presentations with polylux so I've never run into such issues, but I will look into that. Good catch, though!
Did you try using the polux outline mechanism from the `helpers` module?

**Comment by sitandr** [comment]
Can you clarify a bit, please? I didn't want any outline at all at that time, so I didn't use anything.

I can replace outline code of "simple" theme with outline mechanism from `helpers` (and probably make a PR), if that is what you are suggesting.

**Comment by andreasKroepelin** [comment]
Oh I see. Well, I will have to take a look at it.

Just so I know how to test it, does something like this show the effect for you?

```typ
#import "@preview/polylux:0.2.0": *
#import themes.simple: *

#show: simple-theme

#slide[
  #lorem(10000)
]
```

**Comment by sitandr** [comment]
Yep, `lorem(10000)` is enough. It works (I mean it doesn't), I tested it. Even if you create another slide there and try writing something, incremental compilation will not work.

**Comment by andreasKroepelin** [comment]
Okay, thanks for testing!

**Comment by sitandr** [comment]
Probably related: https://github.com/typst/typst/issues/1958.

**Comment by laurmaedje** [comment]
This can be closed. :)
Upstream is fixed: https://github.com/typst/typst/issues/1958
