### ISSUE TITLE
Show the actual page number

### ISSUE THREAD

**Issue by chengluyu** [andreasKroepelin/polylux#75]
Is there a standard way to show the _actual_ page numbers (ignoring slides generated by uncovering functions)?

By reading the source code I found I can achieve it with 
```typst
#set page(
  paper: "presentation-16-9",
  fill: orange.lighten(95%),
  footer: [
    #set text(size: 0.5em)
    #h(1fr)
    #counter("logical-slide").display("1")
  ]
)
```
(this works because counters are globally accessible via their names)

But I think it is better to have a standard way. My solution feels like an abstraction leakage.

**Comment by andreasKroepelin** [comment]
You picked the correct counter. The intended way to access it is as `logic.logical-slide`. Currently (in v0.2.0), there is a bug though, making `logic` difficult to access. This is already fixed on the `main` branch.
