### ISSUE TITLE
Handout mode doesn't handle `#pause`

### ISSUE THREAD

**Issue by AltGr** [andreasKroepelin/polylux#92]
The new `#pause` is great, but unaffected by `#enable-handout-mode(true)`

An option I am wondering about would be to take only the last version of each slide instead of tweaking the separate functions. I don't know if it would be simpler implementation-wise, but I think that's what would suit my use-case best regarding `alternatives`.

**Comment by andreasKroepelin** [comment]
Oh no! I missed that, thanks for pointing it out. It is easy to fix though, I think.

I think it is not trivial to get the last subslide without emmitting all previous ones, though.

**Comment by Drodt** [comment]
> An option I am wondering about would be to take only the last version of each slide instead of tweaking the separate functions

*If* that were to be implemented, it should be an option imo. The current (intended) behavior is ideal in most situations

**Comment by augustebaum** [comment]
I notice this is still an issue since there hasn't been a new release since August 28; would it be possible to make this available?

**Comment by andreasKroepelin** [comment]
I'm hoping to publish a release during my christmas holidays.
