### ISSUE TITLE
Full slide images with metropolis theme, break out of margins.

### ISSUE THREAD

**Issue by willismonroe** [andreasKroepelin/polylux#98]
Maybe I just don't know how to do this in Typst, but I'm using the metropolis theme for preparing lecture slides and every so often I want to have a image take up the full slide (or full height if it's part of a column). The default margins for slides are pretty aggressive (and good for text!) but they make images look too small.

Is there a way for an image to breakout of the margins and take up a full dimension of the slide?

**Comment by andreasKroepelin** [comment]
From the top of my head, can you try `#image("path", width: 110%)` or something like that?

**Comment by willismonroe** [comment]
One suggestion from the discord was using it as a background image, or manually calculating the positiong with the `pad` command.
